# -*- coding: utf-8 -*-
"""
指标字典（唯一口径来源）。
每个指标: 类别 / 定义 / 分子 / 分母 / 粒度 / 排除规则 / 来源表 / 业务意义。
live_sql 为可实时计算的口径 SQL（只读, 返回单值）。
"""

METRICS = [
    # ---------- 北极星 ----------
    dict(类别="北极星", 指标="有效履约用户率",
         定义="成功发放后在14天观察窗口内完成有效兑换且最终履约成功的用户占比",
         分子="14天内有效核销且履约成功的用户数(distinct user)",
         分母="成功发放用户数", 粒度="用户级",
         排除规则="退款订单、履约失败订单不计入分子",
         来源表="dws_user_campaign",
         业务意义="员工体验的最终结果——核销了但没拿到权益等于没发；同时把供应商质量纳入考核",
         live_sql="""SELECT ROUND(SUM(CASE WHEN redeemed_14d_flag=1 AND fulfilled_flag=1
                     THEN 1 ELSE 0 END)*100.0/SUM(issued_flag),1) FROM dws_user_campaign"""),
    # ---------- Funnel 主口径 ----------
    dict(类别="Funnel", 指标="发放成功率",
         定义="卡券成功发放到员工账户的用户占比",
         分子="issue_status='success' 的用户数", 分母="符合资格用户数(eligible)",
         粒度="用户级", 排除规则="按用户去重；一人多券只算一次",
         来源表="fact_coupon_issuance / dws_user_campaign",
         业务意义="衡量名单质量与发放接口稳定性；失败原因: 账号异常/接口超时/名单缺失",
         live_sql="SELECT ROUND(SUM(issued_flag)*100.0/COUNT(*),1) FROM dws_user_campaign"),
    dict(类别="Funnel", 指标="触达率",
         定义="至少一条消息成功送达的用户占比",
         分子="至少一次 delivery_status='delivered' 的用户数(distinct)", 分母="成功发放用户数",
         粒度="用户级", 排除规则="发送成功≠送达; 多次触达只算一次; 打开≠访问",
         来源表="fact_touch / dws_user_campaign",
         业务意义="消息通道健康度；低触达先查联系方式有效性和渠道限制",
         live_sql="SELECT ROUND(SUM(reached_flag)*100.0/SUM(issued_flag),1) FROM dws_user_campaign"),
    dict(类别="Funnel", 指标="累计访问率",
         定义="进入活动页面(任意活动页或权益详情页成功加载)的用户占比",
         分子="有 page_view 事件的用户数(distinct)", 分母="成功发放用户数",
         粒度="用户级", 排除规则="以首次有效事件计; 需对齐时区; 埋点丢失需用领取行为兜底",
         来源表="fact_user_event / dws_user_campaign",
         业务意义="与触达率联看定位'收到但没进来'的断点(本项目最大掉点之一)",
         live_sql="SELECT ROUND(SUM(visited_flag)*100.0/SUM(issued_flag),1) FROM dws_user_campaign"),
    dict(类别="Funnel", 指标="触达到访问率",
         定义="成功触达用户中进入活动页面的比例(条件转化)",
         分子="访问用户数", 分母="成功触达用户数",
         粒度="用户级", 排除规则="同累计访问率",
         来源表="dws_user_campaign",
         业务意义="剥离通道问题后看文案/入口/发送时间的效果, 是消息模板A/B的主指标",
         live_sql="SELECT ROUND(SUM(visited_flag)*100.0/SUM(reached_flag),1) FROM dws_user_campaign"),
    dict(类别="Funnel", 指标="累计领取率",
         定义="成功领取权益(权益进入员工账户)的用户占比",
         分子="claim_status='success' 的用户数(distinct)", 分母="成功发放用户数",
         粒度="用户级", 排除规则="领取≠兑换≠履约, 三者必须分开",
         来源表="fact_claim / dws_user_campaign",
         业务意义="意愿信号: 领取了说明权益匹配, 未核销多是遗忘/有效期问题",
         live_sql="SELECT ROUND(SUM(claimed_flag)*100.0/SUM(issued_flag),1) FROM dws_user_campaign"),
    dict(类别="Funnel", 指标="访问到领取率",
         定义="访问用户中完成领取的比例(条件转化)",
         分子="领取用户数", 分母="访问用户数", 粒度="用户级",
         排除规则="同累计领取率", 来源表="dws_user_campaign",
         业务意义="页面与权益匹配度: 低则查权益结构/页面复杂度, 对应权益推荐优化",
         live_sql="SELECT ROUND(SUM(claimed_flag)*100.0/SUM(visited_flag),1) FROM dws_user_campaign"),
    dict(类别="Funnel", 指标="14天核销率",
         定义="发放后14天内完成有效核销的用户占比(活动核心转化指标)",
         分子="14天窗口内有效核销用户数(distinct)", 分母="成功发放用户数",
         粒度="用户级", 排除规则="排除测试/重复/取消/全额退款/系统补单订单; 只保留首次有效核销",
         来源表="fact_redemption_order / dws_user_campaign",
         业务意义="客户结算和续约判断的核心; 注意基线窗口(Day0-14)与实验窗口(Day14-28)不同",
         live_sql="SELECT ROUND(SUM(redeemed_14d_flag)*100.0/SUM(issued_flag),1) FROM dws_user_campaign"),
    dict(类别="Funnel", 指标="领取后核销率",
         定义="已领取用户中完成有效核销的比例(条件转化)",
         分子="有效核销用户数", 分母="成功领取用户数", 粒度="用户级",
         排除规则="同14天核销率", 来源表="dws_user_campaign",
         业务意义="'领了忘用'的量化, 是到期提醒实验的直接动机(本项目另一大掉点)",
         live_sql="SELECT ROUND(SUM(redeemed_14d_flag)*100.0/SUM(claimed_flag),1) FROM dws_user_campaign"),
    dict(类别="Funnel", 指标="履约成功率",
         定义="有效核销订单中供应商成功交付的比例",
         分子="fulfillment_status='success' 订单数", 分母="有效核销订单数",
         粒度="订单级", 排除规则="失败原因分类: 库存不足/兑换码延迟/接口异常",
         来源表="fact_fulfillment / fact_redemption_order",
         业务意义="供应商质量护栏; 核销升但履约降=体验恶化",
         live_sql="""SELECT ROUND(SUM(CASE WHEN fulfillment_status='success' THEN 1 ELSE 0 END)
                     *100.0/COUNT(*),1) FROM fact_fulfillment"""),
    dict(类别="Funnel", 指标="预算使用率",
         定义="已结算金额占活动批准预算的比例",
         分子="有效核销订单结算金额合计", 分母="活动批准预算(benefit_budget)",
         粒度="金额", 排除规则="退款订单结算金额需冲销",
         来源表="fact_redemption_order / dim_campaign",
         业务意义="客户视角的活动价值; 过低影响续约, 过高需检查预算控制",
         live_sql="""SELECT ROUND(SUM(o.settlement_amount)*100.0/MAX(c.benefit_budget),1)
                     FROM fact_redemption_order o CROSS JOIN dim_campaign c
                     WHERE o.redemption_status='success'"""),
    # ---------- 实验 ----------
    dict(类别="实验", 指标="实验期14天核销率(Primary)",
         定义="实验分组后14天内完成有效核销的用户占比",
         分子="分组后14天内有效核销的实验用户数", 分母="该组有效实验用户数",
         粒度="用户级", 排除规则="资格7条件: 已发放/已触达/已访问/未核销/未过期/无投诉/近期无实验触达",
         来源表="fact_experiment_assignment + dws_user_campaign(exp_redeemed_flag)",
         业务意义="注意窗口: 基线是Day0-14, 实验是Day14-28, 所以Control(28.6%)低于整体(31.2%)是正常的",
         live_sql=None),
    dict(类别="实验", 指标="绝对Lift",
         定义="Treatment核销率 - Control核销率(百分点)",
         分子="—", 分母="—", 粒度="组间对比",
         排除规则="必须先通过SRM检查(卡方1:1:1)和实验前平衡性检验",
         来源表="同上",
         业务意义="Reminder +6.2pp(显著,p≈0.03); Reward再+2.3pp(不显著,p≈0.44)→不建议全量奖励",
         live_sql=None),
    dict(类别="实验", 指标="相对Lift",
         定义="绝对Lift / Control核销率",
         分子="绝对Lift", 分母="Control核销率", 粒度="组间对比",
         排除规则="基线很低时相对Lift会夸大效果, 必须与绝对Lift并列汇报",
         来源表="同上", 业务意义="Reminder相对提升约21.7%", live_sql=None),
    dict(类别="实验", 指标="SRM(样本比例失配)",
         定义="卡方拟合优度检验三组样本量是否符合1:1:1设计",
         分子="—", 分母="—", 粒度="实验级",
         排除规则="p<0.05即警告: 分组机制有问题, 结果作废级别错误",
         来源表="fact_experiment_assignment",
         业务意义="所有实验分析的第一步, 在看任何转化率之前先查",
         live_sql=None),
    dict(类别="实验", 指标="MDE(最小可检测效应)",
         定义="给定样本量/α/Power下能稳定检出的最小效应",
         分子="—", 分母="—", 粒度="设计参数",
         排除规则="500/组、基线28.6%、α=0.05、Power80% → MDE≈8pp",
         来源表="设计文档",
         业务意义="解释为什么单次实验测不出Reward的+2.3pp——应当主动说明这一局限",
         live_sql=None),
    # ---------- 财务 ----------
    dict(类别="财务", 指标="贡献毛利(v2口径)",
         定义="企业结算收入 - 已消耗卡券采购成本 - 过期/不可退损失 - 奖励补贴 - 消息触达成本",
         分子="—", 分母="—", 粒度="金额",
         排除规则="v2与v1区别: 成本按'已消耗采购成本+库存损失'而非简单供应商成本",
         来源表="fact_redemption_order / fact_coupon_inventory / dim_benefit",
         业务意义="御越先采购后结算, 低核销=收入未实现+资金占用+过期损失三重打击",
         live_sql="""SELECT ROUND(SUM(settlement_amount - supplier_cost - reward_cost),0)
                     FROM fact_redemption_order WHERE redemption_status='success'"""),
    dict(类别="财务", 指标="单次增量核销贡献",
         定义="平均企业结算收入 - 平均采购成本(增量一单赚多少)",
         分子="—", 分母="—", 粒度="订单级均值",
         排除规则="只按有效核销订单计算",
         来源表="fact_redemption_order",
         业务意义="ROI计算的基本单元: 增量人数×单次贡献-触达成本-奖励成本",
         live_sql="""SELECT ROUND(AVG(settlement_amount - supplier_cost),1)
                     FROM fact_redemption_order WHERE redemption_status='success'"""),
    dict(类别="财务", 指标="Break-even Reward",
         定义="增量贡献毛利 / 奖励覆盖人数(奖励超过此值必亏)",
         分子="增量贡献毛利", 分母="奖励覆盖人数(核销后发放口径=成功核销人数)",
         粒度="金额/人", 排除规则="区分'全员发'和'核销后发'两种成本口径",
         来源表="实验结果推导",
         业务意义="本项目≈2元/人, 低于拟发放的5元/人 → 不建议全量奖励",
         live_sql=None),
    # ---------- 库存(v2) ----------
    dict(类别="库存", 指标="卡券分配率",
         定义="已分配到活动/员工的卡券占已采购卡券的比例",
         分子="coupon_status != 'available' 的卡券数", 分母="已采购卡券总数",
         粒度="卡券级(coupon_instance_id)", 排除规则="与用户级口径分开, 不可混用",
         来源表="fact_coupon_inventory",
         业务意义="采购是否过量的第一信号",
         live_sql="""SELECT ROUND(SUM(CASE WHEN coupon_status!='available' THEN 1 ELSE 0 END)
                     *100.0/COUNT(*),1) FROM fact_coupon_inventory"""),
    dict(类别="库存", 指标="卡券核销率",
         定义="已核销卡券占已分配卡券的比例",
         分子="coupon_status='redeemed' 卡券数", 分母="已分配卡券数",
         粒度="卡券级", 排除规则="注意与用户核销率(31.2%, 分母为发放用户)数值不同、口径不同",
         来源表="fact_coupon_inventory",
         业务意义="卡券消化效率; HR报表对不上的常见根源就是券级vs人级",
         live_sql="""SELECT ROUND(SUM(CASE WHEN coupon_status='redeemed' THEN 1 ELSE 0 END)
                     *100.0/SUM(CASE WHEN coupon_status!='available' THEN 1 ELSE 0 END),1)
                     FROM fact_coupon_inventory"""),
    dict(类别="库存", 指标="库存老化率(30天)",
         定义="距到期不足30天的未核销卡券占未核销库存的比例",
         分子="expiry_time≤观察时点+30天 的未核销卡券", 分母="全部未核销卡券",
         粒度="卡券级", 排除规则="观察时点=活动复盘日(Day34); 分7/14/30天三档",
         来源表="fact_coupon_inventory",
         业务意义="到期风险预警; 临期券优先用于高Lift人群或转入后续活动",
         live_sql=None),
    dict(类别="库存", 指标="不可退临期风险敞口",
         定义="不可退且临期(30天)未核销卡券数 × 采购成本",
         分子="—", 分母="—", 粒度="金额",
         排除规则="只计refundable_flag=false的权益(电影/健康)",
         来源表="fact_coupon_inventory / dim_benefit",
         业务意义="唯一直接变成损失的库存指标, 本项目≈7.3万元",
         live_sql=None),
    dict(类别="库存", 指标="未消化库存资金占用",
         定义="未核销且不可即时退款卡券 × 采购成本",
         分子="—", 分母="—", 粒度="金额",
         排除规则="可退卡券理论上可收回, 单独列示",
         来源表="fact_coupon_inventory / dim_benefit",
         业务意义="现金流视角: 先采购模式的核心风险, 决定分批采购策略",
         live_sql=None),
    # ---------- 护栏 ----------
    dict(类别="护栏", 指标="投诉率",
         定义="发生投诉的用户/订单占比",
         分子="complaint_flag=1", 分母="实验组用户数或订单数(按场景)",
         粒度="用户级/订单级", 排除规则="实验中按组对比, 恶化即停",
         来源表="fact_fulfillment / dws_user_campaign",
         业务意义="防消息打扰与履约恶化; 不可逆损耗, 比核销率优先级高",
         live_sql="""SELECT ROUND(AVG(complaint_flag)*100,2) FROM dws_user_campaign
                     WHERE issued_flag=1"""),
    dict(类别="护栏", 指标="退款率",
         定义="退款订单占有效核销订单的比例",
         分子="redemption_status='refunded' 订单数", 分母="核销订单总数",
         粒度="订单级", 排除规则="全额退款订单同时要从有效核销中剔除",
         来源表="fact_redemption_order",
         业务意义="低质量兑换信号; 与投诉率联看定位供应商问题",
         live_sql="""SELECT ROUND(SUM(CASE WHEN redemption_status='refunded' THEN 1 ELSE 0 END)
                     *100.0/COUNT(*),2) FROM fact_redemption_order"""),
    dict(类别="护栏", 指标="单次增量核销成本",
         定义="(消息成本+奖励成本) / 增量核销人数",
         分子="干预总成本", 分母="增量核销人数(Lift×组样本)",
         粒度="金额/人", 排除规则="必须用增量人数而非总核销人数, 否则补贴Sure Thing被掩盖",
         来源表="实验结果推导",
         业务意义="补贴过度的刹车指标; 超过单次增量贡献(≈12元)即亏",
         live_sql=None),
    dict(类别="护栏", 指标="供应商履约失败率",
         定义="按供应商统计的履约失败订单占比",
         分子="该供应商失败订单", 分母="该供应商总订单",
         粒度="订单级×供应商", 排除规则="失败原因需分类(库存/延迟/接口)",
         来源表="fact_fulfillment",
         业务意义="SUP04(电影)最高——供应商容量约束进入Policy Simulation的依据",
         live_sql=None),
    # ---------- 长期 ----------
    dict(类别="长期", 指标="下一活动参与率",
         定义="本次活动用户在下一活动中访问或领取的比例",
         分子="下一活动有参与行为的用户", 分母="本次成功发放用户",
         粒度="用户级", 排除规则="替代互联网式日留存——福利场景低频, 传统留存无意义",
         来源表="跨活动 dws (需多批次数据)",
         业务意义="长期价值指标; 需真实后续批次验证, demo 中不给出未验证数值",
         live_sql=None),
    dict(类别="长期", 指标="90天再次兑换率",
         定义="90天内再次完成任意权益兑换的用户比例",
         分子="90天内再次兑换用户", 分母="本次有效核销用户",
         粒度="用户级", 排除规则="同上, 需跨活动数据",
         来源表="跨活动 dws",
         业务意义="衡量福利习惯养成, 支撑客户续约评估",
         live_sql=None),
]
